In [260]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv



In [261]:
#importing data
#u = pd.read_csv('user.csv')
r = pd.read_csv('Rating.csv')
#i = pd.read_csv('item.csv')

In [262]:
print(r)

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
5          298       474       4       884182806
6          115       265       2       881171488
7          253       465       5       891628467
8          305       451       3       886324817
9            6        86       3       883603013
10          62       257       2       879372434
11         286      1014       5       879781125
12         200       222       5       876042340
13         210        40       3       891035994
14         224        29       3       888104457
15         303       785       3       879485318
16         122       387       5       879270459
17         194       274       2       879539794
18         291      1042       4       874834944
19         234      

In [263]:
Rating=r.ix[:,:].values


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


In [264]:
print(Rating)

[[      196       242         3 881250949]
 [      186       302         3 891717742]
 [       22       377         1 878887116]
 ..., 
 [      276      1090         1 874795795]
 [       13       225         2 882399156]
 [       12       203         3 879959583]]


In [265]:
Mod_Rating=Rating[:,[0,1,2]]
print(Mod_Rating)

[[ 196  242    3]
 [ 186  302    3]
 [  22  377    1]
 ..., 
 [ 276 1090    1]
 [  13  225    2]
 [  12  203    3]]


In [266]:
data = np.zeros((943,1682))
print(data)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [267]:
print(len(Mod_Rating))
for i in range(100000):
    u=Mod_Rating[i,0]
    it=Mod_Rating[i,1]
    r=Mod_Rating[i,2]
    data[u-1,it-1]=r
np.savetxt('R.csv',data , delimiter=',', fmt='%10.40f')



100000


In [268]:
print(data)

[[ 5.  3.  4. ...,  0.  0.  0.]
 [ 4.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 5.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  5.  0. ...,  0.  0.  0.]]


In [269]:
import random


In [270]:

tr = np.zeros((943,1682))
for i in range(943):
    for j in range (1682):
        tr[i,j]=data[i,j]
te=np.zeros((943,1682))

for i in range(943):
    big=0
    a=[]
    for j in range (1682):
        if(tr[i,j]>big):
            big=tr[i,j]
    for j in range(1682):
        if(tr[i,j]==big):
            a.append(j)
    l=len(a)
    #print(a)
    for k in range(1):
        r=random.randint(0,l-1)
        print(r,end=' ')
        val=a[r]
        print(val)
        te[i,val]=tr[i,val]
        tr[i,val]=0

            
np.savetxt('train.csv', tr, delimiter=',', fmt='%10.40f')
np.savetxt('test.csv', te, delimiter=',', fmt='%10.40f')

72 227
10 310
0 319
9 353
16 381
20 468
79 401
20 650
4 297
42 588
22 744
2 27
56 413
32 523
2 180
8 21
0 149
56 495
1 434
3 495
6 126
26 357
17 407
35 1006
12 407
1 126
0 99
12 257
1 267
0 68
10 1021
1 297
0 312
3 298
0 299
5 882
8 225
48 464
1 301
8 344
0 49
38 495
24 271
23 519
0 0
10 1061
1 301
16 527
5 153
0 252
2 143
22 1008
3 173
2 116
0 21
7 95
3 63
16 167
88 478
29 488
0 299
13 181
1 115
10 174
18 426
0 49
4 404
7 285
16 255
9 587
8 461
24 434
12 186
1 312
2 55
7 134
0 0
3 1159
6 235
5 214
5 317
7 480
19 662
4 193
15 210
1 269
44 522
7 903
17 221
26 142
3 68
22 432
1 14
20 153
1 6
24 483
9 96
6 516
26 1015
1 314
0 236
15 257
0 49
4 268
1 269
4 193
0 268
6 514
36 402
0 160
2 314
7 345
9 326
8 521
27 465
11 595
13 180
23 187
47 715
1 257
10 134
17 707
13 484
2 165
21 172
1 265
3 228
10 135
0 285
4 16
2 99
1 663
0 257
4 747
0 97
9 275
23 404
7 186
1 126
1 302
6 125
2 168
3 325
3 47
13 87
5 1021
3 303
23 472
0 268
0 49
78 486
51 780
3 181
10 237
0 305
1 179
10 272
32 284
7 126
34 

In [271]:
#normalisation of the rating matrix
norm=np.zeros((943,1683))
for i in range(943):
    sum=0
    c=0
    for j in range(1682):
        norm[i,j]=tr[i,j]
        if(tr[i,j]!=0):
            sum+=tr[i,j]
            c+=1
    norm[i,1682]=(sum/c)
for i in range(943):
    for j in range(1682):
        if(norm[i,j]!=0):
            norm[i,j]=norm[i,j]-norm[i,1682]
        
np.savetxt('norm.csv', norm, delimiter=',', fmt='%10.40f')


In [272]:
#similarity calculations w/o normalisation
import math
cossim=np.zeros((1682,1682))
              
for i in range(1682):
    for j in range(i,1682):
        num=0
        d1=0
        d2=0
        for k in range(943):
            num+=tr[k,i]*tr[k,j]
            d1+=math.pow(tr[k,i],2)
            d2+=math.pow(tr[k,j],2)
        s=num/((math.sqrt(d1))*(math.sqrt(d2)))
        cossim[i,j]=s
        cossim[j,i]=s
    print(i)
print(cossim)
np.savetxt('cossim.csv', cossim, delimiter=',', fmt='%10.40f')


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [273]:
#similarity calculations w normalisation
import math
ncossim=np.zeros((1682,1682))
              
for i in range(1682):
    for j in range(i,1682):
        num=0
        d1=0
        d2=0
        for k in range(943):
            num+=norm[k,i]*norm[k,j]
            d1+=math.pow(norm[k,i],2)
            d2+=math.pow(norm[k,j],2)
        s=num/((math.sqrt(d1))*(math.sqrt(d2)))
        ncossim[i,j]=s
        ncossim[j,i]=s
    print(i)
print(ncossim)
np.savetxt('ncossim.csv', ncossim, delimiter=',', fmt='%10.40f')


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in double_scalars
  


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [274]:
#cosine similarity neighbourhood calc w/o normalisation
n1=np.zeros((1682,10))
t=np.zeros((1682,1682))
for i in range(1682):
    for j in range(1682):
        t[i,j]=cossim[i,j]
        
for k in range(10):
    for i in range(1682):
        big=0
        val=0
        for j in range(1682):
            if(t[i,j]>big and i!=j):
                big=t[i,j]
                val=j
        n1[i,k]=(val)
        t[i,val]=-1000
np.savetxt('n1.csv', n1, delimiter=',', fmt='%10.40f')

#cosine similarity neighbourhood calc w normalisation
n2=np.zeros((1682,10))
t=np.zeros((1682,1682))
for i in range(1682):
    for j in range(1682):
        t[i,j]=ncossim[i,j]
        
for k in range(10):
    for i in range(1682):
        big=0
        val=0
        for j in range(1682):
            if(t[i,j]>big and i!=j):
                big=t[i,j]
                val=j
        n2[i,k]=(val)
        t[i,val]=-1000
np.savetxt('n2.csv', n2, delimiter=',', fmt='%10.40f')


In [275]:
#Probability similarity calc w/o normalisation
ps=np.zeros((1682,1682))

for i in range(1682):
    for j in range(1682):
        num=0
        f1=0
        f2=0
        for k in range(943):
            if(tr[k,i]!=0):
                num+=tr[k,j]
                f1+=1
            if(tr[k,j]!=0):
                f2+=1
        ps[i,j]=num/(f1*(math.pow(f2,0.5)))
    print(i)
print(ps)
np.savetxt('probsim.csv', ps, delimiter=',', fmt='%10.40f')


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

KeyboardInterrupt: 

In [ ]:
print(ps)

In [ ]:
#Probability calc w normalisation
nps=np.zeros((1682,1682))

for i in range(1682):
    for j in range(1682):
        num=0
        f1=0
        f2=0
        for k in range(943):
            if(norm[k,i]!=0):
                num+=norm[k,j]
                f1+=1
            if(norm[k,j]!=0):
                f2+=1
        if(f1*(math.pow(f2,0.5))!=0):
            nps[i,j]=num/(f1*(math.pow(f2,0.5)))
        else:
            nps[i,j]=0
    print(i)
print(nps)


In [ ]:
np.savetxt('nprobsim.csv', nps, delimiter=',', fmt='%10.40f')
print(norm)

In [ ]:
#probability similarity neighbourhood calc w/o normalisation
n3=np.zeros((1682,10))
t=np.zeros((1682,1682))
for i in range(1682):
    for j in range(1682):
        t[i,j]=ps[i,j]
        
for k in range(10):
    for i in range(1682):
        big=0
        val=0
        for j in range(1682):
            if(t[i,j]>big and i!=j):
                big=t[i,j]
                val=j
        n3[i,k]=(val)
        t[i,val]=-1000
np.savetxt('n3.csv', n3, delimiter=',', fmt='%10.40f')

#probability similarity neighbourhood calc w normalisation
n4=np.zeros((1682,10))
t=np.zeros((1682,1682))
for i in range(1682):
    for j in range(1682):
        t[i,j]=nps[i,j]
        
for k in range(10):
    for i in range(1682):
        big=0
        val=0
        for j in range(1682):
            if(t[i,j]>big and i!=j):
                big=t[i,j]
                val=j
        n4[i,k]=(val)
        t[i,val]=-1000
np.savetxt('n4.csv', n4, delimiter=',', fmt='%10.40f')


In [ ]:
#Item-based Top_N Collaborative filtering

U=np.zeros((943,1682))
for i in range(943):
    c=0
    for j in range(1682):
        if(tr[i,j]!=0):
            U[i,c]=(j+1)
            c+=1

np.savetxt('U.csv', U, delimiter=',', fmt='%10.40f')



In [ ]:

#print(k)
C=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n1[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C[i]
        if(Un[n] not in ar):
            C[i,c]=Un[n]
            c+=1
        
print(C)
np.savetxt('C.csv', C, delimiter=',', fmt='%10.40f')


In [ ]:
#Calculating the final C
for i in range(943):
    for j in range(1682):
        val=C[i,j]
        for k in range(1682):
            v=U[i,k]
            if(val==v):
                C[i,j]=-1
    print(i)
print(C)
np.savetxt('Cf.csv', C, delimiter=',', fmt='%10.40f')


In [ ]:
np.savetxt('Cf.csv', C, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding similarity between C and U with cosine similarity
S=np.zeros((943,1682))

for i in range(943):
    c=C[i]
    u=U[i]
    for j in range(1682):
        sim=[]
        val=c[j]
        sums=0
        if(val>=0):
            for k in range(1682):
                if((u[k]-1)>=0):
                    v=int(u[k])-1
                    s=cossim[int(val),int(v)]
                    sim.append(s)
            sim=sorted(sim, key=abs, reverse=True)
            #print(len(sim),end=' ')
            for l in range(10):
                sums+=sim[l]
            S[i,j]=sums
    print(i)

np.savetxt('Csim.csv', S, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding the top N items 
tpn=np.zeros((943,10))

Scpy=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        Scpy[i,j]=S[i,j]


for i in range(943):
    for k in range(10):
        big=0
        val=0
        for j in range(1682):
            if(Scpy[i,j]>big):
                big=Scpy[i,j]
                val=j
        tpn[i,k]=C[i,val]
        Scpy[i,val]=-1
np.savetxt('topn.csv', tpn, delimiter=',', fmt='%10.40f')


In [ ]:
#Recall calculation
rec1=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec1=res/943
print(rec1)

In [ ]:
#print(k)
C1=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C1[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n2[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C1[i]
        if(Un[n] not in ar):
            C1[i,c]=Un[n]
            c+=1
        
print(C1)
np.savetxt('C1.csv', C1, delimiter=',', fmt='%10.40f')

In [ ]:
#Calculating the final C1
for i in range(943):
    for j in range(1682):
        val=C1[i,j]
        for k in range(1682):
            v=U[i,k]
            if(val==v):
                C1[i,j]=-1
    print(i)
print(C1)
np.savetxt('Cf1.csv', C1, delimiter=',', fmt='%10.40f')


In [ ]:
#Finding similarity between C and U with cosine similarity
S1=np.zeros((943,1682))
for i in range(943):
    c=C1[i]
    u=U[i]
    for j in range(1682):
        sim=[]
        val=c[j]
        sums=0
        if(val>=0):
            for k in range(1682):
                if((u[k]-1)>=0):
                    v=int(u[k])-1
                    s=ncossim[int(val),int(v)]
                    sim.append(s)
            sim=sorted(sim, reverse=True)
            #print(sim)
            for l in range(10):
                sums+=sim[l]
            S1[i,j]=sums
    print(i)

np.savetxt('nCsim.csv', S1, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding the top N items 
tpn1=np.zeros((943,10))

Scpy=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        Scpy[i,j]=S1[i,j]


for i in range(943):
    for k in range(10):
        big=0
        val=0
        for j in range(1682):
            if(Scpy[i,j]>big):
                big=Scpy[i,j]
                val=j
        tpn1[i,k]=C1[i,val]
        Scpy[i,val]=-1
    print(i)
np.savetxt('topn1.csv', tpn1, delimiter=',', fmt='%10.40f')

In [ ]:
#Recall calculation
rec2=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn1[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec2=res/943
print(rec2)

In [ ]:
#print(k)
C2=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C2[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n3[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C2[i]
        if(Un[n] not in ar):
            C2[i,c]=Un[n]
            c+=1
        
print(C2)
np.savetxt('C2.csv', C2, delimiter=',', fmt='%10.40f')

In [ ]:
#Calculating the final C
for i in range(943):
    for j in range(1682):
        val=C2[i,j]
        for k in range(1682):
            v=U[i,k]
            if(val==v):
                C2[i,j]=-1
    print(i)
print(C2)
np.savetxt('Cf2.csv', C2, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding similarity between C and U with prob similarity
S2=np.zeros((943,1682))


for i in range(943):
    c=C2[i]
    u=U[i]
    for j in range(1682):
        sim=[]
        val=c[j]
        sums=0
        if(val>=0):
            for k in range(1682):
                if((u[k]-1)>=0):
                    v=int(u[k])-1
                    s=ps[int(val),int(v)]
                    sim.append(s)
            sim=sorted(sim, key=abs, reverse=True)
            #print(len(sim),end=' ')
            for l in range(10):
                sums+=sim[l]
            S2[i,j]=sums
    print(i)

np.savetxt('Csim2.csv', S2, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding the top N items 
tpn2=np.zeros((943,10))

Scpy=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        Scpy[i,j]=S2[i,j]
print(Scpy)

for i in range(943):
    for k in range(10):
        big=0
        val=0
        for j in range(1682):
            if(Scpy[i,j]>big):
                big=Scpy[i,j]
                val=j
            #print(val)
        tpn2[i,k]=C2[i,val]
        #print(C2[i,val])
        Scpy[i,val]=-1
    
np.savetxt('topn2.csv', tpn2, delimiter=',', fmt='%10.40f')


In [ ]:
#Recall calculation
rec3=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn2[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec3=res/943
print(rec3)

In [ ]:
C3=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        C3[i,j]=-1

for i in range(943):
    Un=[]
    for j in range(1682):
        if(U[i,j]!=0):
            val=U[i,j]
            for m in range(10):
                Un.append(n4[int(val-1),m])
    print(i)
    l=len(Un)
    c=0
    for n in range(l):
        ar=C3[i]
        if(Un[n] not in ar):
            C3[i,c]=Un[n]
            c+=1
        
print(C3)
np.savetxt('C3.csv', C3, delimiter=',', fmt='%10.40f')

In [ ]:
#Calculating the final C
for i in range(943):
    for j in range(1682):
        val=C3[i,j]
        for k in range(1682):
            v=U[i,k]
            if(val==v):
                C3[i,j]=-1
    print(i)
print(C3)
np.savetxt('Cf3.csv', C3, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding similarity between C and U with cosine similarity
S3=np.zeros((943,1682))


for i in range(943):
    c=C3[i]
    u=U[i]
    for j in range(1682):
        sim=[]
        val=c[j]
        sums=0
        if(val>=0):
            for k in range(1682):
                if((u[k]-1)>=0):
                    v=int(u[k])-1
                    s=nps[int(val),int(v)]
                    sim.append(s)
            sim=sorted(sim, key=abs, reverse=True)
            #print(len(sim),end=' ')
            for l in range(10):
                sums+=sim[l]
            S3[i,j]=sums
    print(i)

np.savetxt('Csim3.csv', S3, delimiter=',', fmt='%10.40f')

In [ ]:
#Finding the top N items 
tpn3=np.zeros((943,10))

Scpy=np.zeros((943,1682))
for i in range(943):
    for j in range(1682):
        Scpy[i,j]=S3[i,j]


for i in range(943):
    for k in range(10):
        big=0
        val=0
        for j in range(1682):
            if(Scpy[i,j]>big):
                big=Scpy[i,j]
                val=j
        tpn3[i,k]=C3[i,val]
        Scpy[i,val]=-1
np.savetxt('topn3.csv', tpn3, delimiter=',', fmt='%10.40f')


In [ ]:
#Recall calculation
rec4=0
res=0
for i in range(943):
    for j in range(10):
        val=tpn3[i,j]
        if(te[i,int(val)]!=0):
            res+=1
rec4=res/943
print(rec4)